services:
  - type: web
    name: lost2found
    env: node
    buildCommand: npm install
    startCommand: node app.js
    disk:
      name: lost2found-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        value: dsjvyjitj
      - key: CLOUDINARY_API_KEY
        value: 861811256413455
      - key: CLOUDINARY_FOLDER
        value: lost2found
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASS
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_NAME
        sync: false
      - key: ADMIN_STUDENT_ID
        value: ADMIN-0001
      - key: APP_URL
        sync: false
      - key: TURSO_DATABASE_URL
        value: libsql://lost2found-almaynulhasan.aws-ap-south-1.turso.io
      - key: TURSO_AUTH_TOKEN
        sync: false
